name: Generate ASCII dragon art

on: push

jobs:
  Build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: install cowsay for generating ascii
      run: sudo apt install cowsay -y

    - name: execute cosay command
      run: cowsay -f dragon "I'm Shanron you have 1 wish to fullfil!! ask now!" >> dragon.txt

    - name: upload dragon artifact
      uses: actions/upload-artifact@v4
      with:
        name: dragon-artifact-txt
        path: dragon.txt
    
    - name: sleep for 10
      run: sleep 10

  Test_job_2:
    needs: Build_job_1
    runs-on: ubuntu-latest
    steps:
    - name: download dragon artifact
      uses: actions/download-artifact@v4
      with:
        name: dragon-artifact-txt
    
    - name: test dragon artifact file exist
      run: grep -i 'Shanron' dragon.txt

  Deploy_job_3:
    needs: Test_job_2
    runs-on: ubuntu-latest
    steps:
    - name: download dragon artifact
      uses: actions/download-artifact@v4
      with:
        name: dragon-artifact-txt
    
    - name: read file
      run: cat dragon.txt